[build]
builder = "dockerfile"

[deploy]
startCommand = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT --log-level info"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

# Resource requirements for Playwright
[resources]
memory = "2Gi"
cpu = "1000m"

[env]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app"
# Playwright environment variables for production
PLAYWRIGHT_BROWSERS_PATH = "/ms-playwright"
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "false" 