[build]
builder = "dockerfile"

[deploy]
startCommand = "python start_server.py --host 0.0.0.0 --port $PORT --no-reload"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

# Resource requirements for Playwright
[resources]
memory = "2Gi"
cpu = "1000m"

[env]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app" 