[build]
builder = "dockerfile"

[deploy]
startCommand = "./startup.sh"
healthcheckPath = "/health"
healthcheckTimeout = 600
restartPolicyType = "on_failure"

# Resource requirements for Playwright
[resources]
memory = "2Gi"
cpu = "1000m"

[env]
PYTHONUNBUFFERED = "1"
PYTHONPATH = "/app"
# Playwright environment variables for production
PLAYWRIGHT_BROWSERS_PATH = "/ms-playwright"
PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD = "false" 